version: '3.7'

volumes:
  db_vol:

networks:
  db_net:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.10.0/24

services:
  db:
    image: mahendrshinde/mysql-sample:sakila
    volumes:
      - db_vol:/var/lib/mysql
    networks:
    - db_net
    ports:
      - 3306:3306
 

  client:
    image: adminer
    networks:
    - db_net
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 8080:8080
    depends_on:
    - db